import { firebaseConfig } from './firebase-config.js';

const $ = (s, r=document)=>r.querySelector(s);
const $$ = (s, r=document)=>[...r.querySelectorAll(s)];
const money = n => Number(n||0).toLocaleString('vi-VN')+'đ';
const pct = n => Math.round(n*100)/100;
const uid = p => `${p}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
const deep = o => JSON.parse(JSON.stringify(o));

const MENUS = [
  ['dashboard','Dashboard'],['evaluations','Đánh giá tháng'],['workflow','Quy trình duyệt'],['employees','CBGVNV'],
  ['criteria','Tiêu chí & thang điểm'],['bonusPenalty','Điểm cộng / trừ'],['categories','Danh mục'],
  ['reports','Báo cáo'],['audit','Nhật ký thay đổi'],['settings','Cấu hình Firebase']
];
const RANKS = [
  {code:'HTXSNV', name:'Hoàn thành xuất sắc nhiệm vụ', min:90, coef:.5, tag:'green'},
  {code:'HTTNV', name:'Hoàn thành tốt nhiệm vụ', min:80, coef:.3, tag:'purple'},
  {code:'HTNV', name:'Hoàn thành nhiệm vụ', min:65, coef:.1, tag:'amber'},
  {code:'KHTNV', name:'Không hoàn thành nhiệm vụ', min:0, coef:0, tag:'red'}
];
const DEFAULT = {
 school:{name:'THCS Trưng Vương Đà Nẵng', address:'Đà Nẵng'},
 selectedYear:'2026-2027', selectedPeriod:'2026-08', lockedPeriods:[],
 years:['2026-2027','2027-2028'], periods:['2026-08','2026-09','2026-10','2026-11','2026-12','2027-01','2027-02','2027-03','2027-04','2027-05'],
 departments:['Ban giám hiệu','Tổ Toán - Tin','Tổ Ngữ văn','Tổ Ngoại ngữ','Tổ KHTN','Tổ KHXH','Tổ Văn phòng'],
 positions:['Hiệu trưởng','Phó Hiệu trưởng','Tổ trưởng','Giáo viên','Nhân viên'],
 roles:['ADMIN','HIEU_TRUONG','BGH','TO_TRUONG','GIAO_VIEN','KE_TOAN','VIEWER'],
 criteria:[
  {id:'c1', group:'Tiêu chí chung', name:'Phẩm chất chính trị, đạo đức, lối sống', max:10, required:true},
  {id:'c2', group:'Tiêu chí chung', name:'Ý thức kỷ luật, kỷ cương', max:5, required:true},
  {id:'c3', group:'Tiêu chí chung', name:'Năng lực chuyên môn, nghiệp vụ', max:10, required:true},
  {id:'c4', group:'Tiêu chí chung', name:'Thái độ phục vụ và phối hợp', max:5, required:true},
  {id:'c5', group:'Kết quả thực hiện nhiệm vụ', name:'Khối lượng tiết dạy / khối lượng công việc', max:20, required:true},
  {id:'c6', group:'Kết quả thực hiện nhiệm vụ', name:'Chất lượng bài giảng / chất lượng sản phẩm công việc', max:25, required:true},
  {id:'c7', group:'Kết quả thực hiện nhiệm vụ', name:'Tiến độ hoàn thành hồ sơ, sổ sách, báo cáo', max:15, required:true},
  {id:'c8', group:'Kết quả thực hiện nhiệm vụ', name:'Sáng kiến, phối hợp nhiệm vụ chung, đóng góp đột xuất', max:10, required:false}
 ],
 bonusTypes:[
  {id:'b1', name:'Thành tích đột xuất cấp trường', point:1}, {id:'b2', name:'Thành tích cấp quận/thành phố', point:2}, {id:'b3', name:'Nhiệm vụ chung toàn trường nổi bật', point:1}
 ],
 penaltyTypes:[
  {id:'p1', name:'Chậm hồ sơ/sổ sách', point:2}, {id:'p2', name:'Không tham gia sinh hoạt chuyên môn', point:2}, {id:'p3', name:'Vi phạm kỷ luật/kỷ cương', point:5}, {id:'p4', name:'Thiếu minh chứng bắt buộc', point:3}
 ],
 employees:[], evaluations:[], audit:[], settings:{quotaTeam:.10, quotaCouncil:.10, baseSalary:2340000, bonusCap:6, maxScore:100, minExcellentMonthsForYear:2, maxHTNVMonthsForYear:2}
};
let state = load(); let route = 'dashboard'; let charts=[];
function load(){ try{return {...deep(DEFAULT), ...JSON.parse(localStorage.getItem('tv_eval_state')||'{}')}}catch{return deep(DEFAULT)} }
function save(action='Lưu dữ liệu'){ localStorage.setItem('tv_eval_state', JSON.stringify(state)); log(action); refreshSelectors(); }
function log(action){ state.audit ||= []; state.audit.unshift({id:uid('log'), time:new Date().toLocaleString('vi-VN'), user:'Admin', action}); state.audit=state.audit.slice(0,500); localStorage.setItem('tv_eval_state', JSON.stringify(state)); }
function toast(msg){ const el=document.createElement('div'); el.className='toast'; el.textContent=msg; $('#toast').append(el); setTimeout(()=>el.remove(),2600); }
function rank(score){ return RANKS.find(r=>score>=r.min)||RANKS.at(-1); }
function periodName(p){ const [y,m]=p.split('-'); return `Tháng ${Number(m)}/${y}`; }
function isLocked(p=state.selectedPeriod){ return state.lockedPeriods?.includes(p); }
function calcEval(ev){
 const sum = Object.values(ev.scores||{}).reduce((a,b)=>a+Number(b||0),0);
 const bonus = Math.min(state.settings.bonusCap, (ev.bonuses||[]).reduce((a,b)=>a+Number(b.point||0),0));
 const penalty = (ev.penalties||[]).reduce((a,b)=>a+Number(b.point||0),0);
 const total = Math.max(0, Math.min(state.settings.maxScore, sum + bonus - penalty));
 return {sum, bonus, penalty, total, rank:rank(total)};
}
function validateEval(ev){
 const errs=[]; for(const c of state.criteria){ const v=Number(ev.scores?.[c.id] ?? -1); if(c.required && (v<0||isNaN(v))) errs.push(`Thiếu điểm: ${c.name}`); if(v>c.max) errs.push(`${c.name} vượt ${c.max} điểm`); }
 const cal=calcEval(ev); if(cal.bonus>state.settings.bonusCap) errs.push(`Điểm cộng vượt trần +${state.settings.bonusCap}`); if(!ev.evidenceCount && ev.status!=='draft') errs.push('Thiếu minh chứng'); if(isLocked(ev.period)) errs.push('Kỳ đánh giá đã khóa'); return errs;
}
function employeesFiltered(){ const q=$('#globalSearch')?.value?.toLowerCase()||''; return state.employees.filter(e=>JSON.stringify(e).toLowerCase().includes(q)); }
function evalsFiltered(){ const q=$('#globalSearch')?.value?.toLowerCase()||''; return state.evaluations.filter(e=>e.year===state.selectedYear && e.period===state.selectedPeriod).filter(ev=>{ const emp=state.employees.find(x=>x.id===ev.employeeId)||{}; return (JSON.stringify(ev)+JSON.stringify(emp)).toLowerCase().includes(q); }); }
function seed(){
 state.employees = ['Nguyễn Văn An','Trần Thị Bình','Lê Minh Châu','Phạm Quốc Dũng','Hoàng Thu Hà','Võ Nhật Linh','Đặng Thanh Tâm','Bùi Lan Anh','Mai Đức Huy','Đỗ Kim Ngân','Hồ Văn Phúc','Ngô Thảo Vy'].map((n,i)=>({id:uid('emp'), code:'CB'+String(i+1).padStart(3,'0'), name:n, department:state.departments[i%state.departments.length], position:state.positions[Math.min(i%5,4)], role:i<1?'HIEU_TRUONG':i<3?'TO_TRUONG':'GIAO_VIEN', active:true, email:`user${i+1}@trungvuong.edu.vn`}));
 state.evaluations=[]; for(const emp of state.employees){ for(const p of state.periods.slice(0,3)){ const scores={}; state.criteria.forEach(c=>scores[c.id]=Math.max(0, Math.min(c.max, Math.round(c.max*(.72+Math.random()*.27))))); state.evaluations.push({id:uid('ev'), employeeId:emp.id, year:state.selectedYear, period:p, scores, bonuses:Math.random()>.7?[{name:'Đóng góp nhiệm vụ chung',point:1}]:[], penalties:Math.random()>.85?[{name:'Chậm hồ sơ',point:2}]:[], evidenceCount:Math.random()>.2?1:0, status:Math.random()>.25?'submitted':'draft', workflow:'Tổ trưởng', note:''}); }}
 save('Tạo dữ liệu mẫu'); toast('Đã tạo dữ liệu mẫu'); render();
}
function refreshSelectors(){
 $('#schoolYear').innerHTML = state.years.map(y=>`<option ${y===state.selectedYear?'selected':''}>${y}</option>`).join('');
 $('#period').innerHTML = state.periods.map(p=>`<option value="${p}" ${p===state.selectedPeriod?'selected':''}>${periodName(p)}</option>`).join('');
}
function init(){ $('#menu').innerHTML=MENUS.map(m=>`<button class="navbtn" data-route="${m[0]}">${m[1]}</button>`).join(''); $$('.navbtn').forEach(b=>b.onclick=()=>{route=b.dataset.route;render()}); $('#btnSeed').onclick=seed; $('#globalSearch').oninput=render; $('#schoolYear').onchange=e=>{state.selectedYear=e.target.value; save('Đổi năm học'); render()}; $('#period').onchange=e=>{state.selectedPeriod=e.target.value; save('Đổi tháng'); render()}; $('#btnSaveFirebase').onclick=syncFirebase; refreshSelectors(); render(); tryFirebase(); }
function layout(title,desc,html){ $('#pageTitle').textContent=title; $('#pageDesc').textContent=desc; $$('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.route===route)); $('#app').innerHTML=html; }
function render(){ charts.forEach(c=>c.destroy?.()); charts=[]; ({dashboard, evaluations, workflow, employees, criteria, bonusPenalty, categories, reports, audit, settings}[route]||dashboard)(); }
function dashboard(){ const evs=evalsFiltered(); const done=evs.filter(e=>e.status!=='draft').length; const ranks=RANKS.map(r=>evs.filter(e=>calcEval(e).rank.code===r.code).length); const missing=state.employees.length-evs.filter(e=>e.status!=='draft').length; layout('Dashboard','Tổng quan chất lượng đánh giá theo tháng, tổ chuyên môn và cảnh báo',`
 <div class="grid cards"><div class="card kpi"><span>Tổng CBGVNV</span><b>${state.employees.length}</b></div><div class="card kpi"><span>Đã nộp đánh giá</span><b>${done}</b></div><div class="card kpi"><span>Chưa nộp</span><b>${Math.max(0,missing)}</b></div><div class="card kpi"><span>Tháng hiện tại</span><b>${periodName(state.selectedPeriod)}</b><span class="tag ${isLocked()?'red':'green'}">${isLocked()?'Đã khóa':'Đang mở'}</span></div></div>
 <div class="grid two" style="margin-top:16px"><div class="card"><h3>Phân bổ xếp loại</h3><canvas id="rankChart"></canvas></div><div class="card"><h3>Cảnh báo nghiệp vụ</h3>${warnings().map(w=>`<div class="alert">${w}</div>`).join('')||'<div class="tag green">Không có cảnh báo lớn</div>'}</div></div>
 <div class="card" style="margin-top:16px"><h3>Thống kê theo tổ</h3><div class="table-wrap"><table><thead><tr><th>Tổ</th><th>Nhân sự</th><th>Đã nộp</th><th>Điểm TB</th><th>HTXSNV</th></tr></thead><tbody>${deptStats().map(d=>`<tr><td>${d.name}</td><td>${d.total}</td><td>${d.done}</td><td>${d.avg}</td><td><span class="tag green">${d.ex}</span></td></tr>`).join('')}</tbody></table></div></div>`);
 const ctx=$('#rankChart'); if(ctx) charts.push(new Chart(ctx,{type:'bar',data:{labels:RANKS.map(r=>r.code),datasets:[{label:'Số lượng',data:ranks}]},options:{plugins:{legend:{display:false}}}}));
}
function warnings(){ const evs=evalsFiltered(); let w=[]; const noEval=state.employees.filter(e=>!evs.some(v=>v.employeeId===e.id&&v.status!=='draft')); if(noEval.length) w.push(`${noEval.length} người chưa nộp đánh giá tháng ${periodName(state.selectedPeriod)}.`); const noEvidence=evs.filter(e=>e.status!=='draft'&&!e.evidenceCount); if(noEvidence.length) w.push(`${noEvidence.length} hồ sơ đã nộp nhưng thiếu minh chứng.`); const ex=evs.filter(e=>calcEval(e).rank.code==='HTXSNV').length; const quota=Math.floor(state.employees.length*(state.settings.quotaTeam+state.settings.quotaCouncil)); if(ex>quota) w.push(`HTXSNV ${ex} người, vượt quota tối đa ${quota} người theo cấu hình 20%.`); return w; }
function deptStats(){ return state.departments.map(name=>{ const emps=state.employees.filter(e=>e.department===name); const evs=evalsFiltered().filter(v=>emps.some(e=>e.id===v.employeeId)); const done=evs.filter(e=>e.status!=='draft').length; const avg=evs.length?pct(evs.reduce((a,e)=>a+calcEval(e).total,0)/evs.length):0; const ex=evs.filter(e=>calcEval(e).rank.code==='HTXSNV').length; return {name,total:emps.length,done,avg,ex}; }); }
function evaluations(){ const evs=evalsFiltered(); layout('Đánh giá tháng','Nhập điểm theo tiêu chí 30/70, điểm cộng tối đa +6, kiểm tra minh chứng và quota',`
 <div class="toolbar"><div class="filters"><select id="fDept"><option value="">Tất cả tổ</option>${state.departments.map(d=>`<option>${d}</option>`)}</select><select id="fRank"><option value="">Tất cả xếp loại</option>${RANKS.map(r=>`<option>${r.code}</option>`)}</select></div><div><button onclick="window.openEval()" class="primary">+ Tạo phiếu đánh giá</button> <button onclick="window.toggleLock()" class="${isLocked()?'warn':'danger'}">${isLocked()?'Mở khóa tháng':'Khóa tháng'}</button></div></div>
 <div class="table-wrap"><table><thead><tr><th>Mã</th><th>Họ tên</th><th>Tổ</th><th>Trạng thái</th><th>Điểm</th><th>Xếp loại</th><th>Minh chứng</th><th>Luồng duyệt</th><th>Thao tác</th></tr></thead><tbody id="evRows">${evRows(evs)}</tbody></table></div><div id="modal" class="modal"></div>`); $('#fDept').onchange=filterEvalTable; $('#fRank').onchange=filterEvalTable; }
function evRows(evs){ return evs.map(ev=>{ const emp=state.employees.find(e=>e.id===ev.employeeId)||{}; const c=calcEval(ev); return `<tr data-dept="${emp.department}" data-rank="${c.rank.code}"><td>${emp.code||''}</td><td><b>${emp.name||''}</b></td><td>${emp.department||''}</td><td><span class="tag ${ev.status==='draft'?'amber':'green'}">${ev.status==='draft'?'Nháp':'Đã nộp'}</span></td><td><b>${c.total}</b></td><td><span class="tag ${c.rank.tag}">${c.rank.code}</span></td><td>${ev.evidenceCount||0}</td><td>${ev.workflow||'Giáo viên'}</td><td class="actions"><button onclick="window.openEval('${ev.id}')">Sửa</button><button class="danger" onclick="window.delEval('${ev.id}')">Xóa</button></td></tr>`; }).join('')||'<tr><td colspan="9">Chưa có dữ liệu. Bấm Tạo dữ liệu mẫu hoặc tạo phiếu mới.</td></tr>'; }
function filterEvalTable(){ const d=$('#fDept').value, r=$('#fRank').value; $$('#evRows tr').forEach(tr=>tr.style.display=(!d||tr.dataset.dept===d)&&(!r||tr.dataset.rank===r)?'':'none'); }
window.openEval=(id='')=>{ const ev=id?deep(state.evaluations.find(e=>e.id===id)):{id:'',employeeId:state.employees[0]?.id||'',year:state.selectedYear,period:state.selectedPeriod,scores:{},bonuses:[],penalties:[],evidenceCount:0,status:'draft',workflow:'Giáo viên',note:''}; const modal=$('#modal'); modal.className='modal open'; modal.innerHTML=`<div class="dialog"><div class="dialog-head"><h2>${id?'Cập nhật':'Tạo'} phiếu đánh giá</h2><button onclick="window.closeModal()">Đóng</button></div><div class="form"><label class="span2">CBGVNV<select id="evEmp">${state.employees.map(e=>`<option value="${e.id}" ${e.id===ev.employeeId?'selected':''}>${e.code} - ${e.name} - ${e.department}</option>`)}</select></label><label>Trạng thái<select id="evStatus"><option value="draft">Nháp</option><option value="submitted" ${ev.status==='submitted'?'selected':''}>Đã nộp</option></select></label><label>Minh chứng<input id="evEvidence" type="number" min="0" value="${ev.evidenceCount||0}"></label><label class="span4">Ghi chú<textarea id="evNote">${ev.note||''}</textarea></label></div><h3>Điểm tiêu chí</h3><div class="criteria-grid">${state.criteria.map(c=>`<div class="criteria-item"><b>${c.name}</b><div class="mini">${c.group} - tối đa ${c.max} điểm</div><input class="scoreInput" data-id="${c.id}" type="number" min="0" max="${c.max}" value="${ev.scores?.[c.id]??''}" placeholder="0-${c.max}"></div>`).join('')}</div><div class="grid two" style="margin-top:12px"><div class="card"><h3>Điểm cộng</h3><div id="bonusBox">${itemList(ev.bonuses,'bonus')}</div><button onclick="window.addLine('bonus')">+ Thêm điểm cộng</button></div><div class="card"><h3>Điểm trừ</h3><div id="penaltyBox">${itemList(ev.penalties,'penalty')}</div><button onclick="window.addLine('penalty')">+ Thêm điểm trừ</button></div></div><div class="toolbar" style="margin-top:14px"><div><div class="scorebox" id="previewScore">0</div><span id="previewRank" class="tag"></span></div><button class="primary" onclick="window.saveEval('${id}')">Lưu phiếu</button></div><div id="errBox"></div></div>`; window.recalcPreview(); $$('.scoreInput').forEach(i=>i.oninput=window.recalcPreview); };
function itemList(items,type){ return (items||[]).map((x,i)=>`<div class="form" style="grid-template-columns:1fr 100px 70px;margin-bottom:8px"><input class="${type}Name" value="${x.name||''}" placeholder="Lý do"><input class="${type}Point" type="number" value="${x.point||0}"><button class="danger" onclick="this.parentElement.remove(); window.recalcPreview()">Xóa</button></div>`).join(''); }
window.addLine=(type)=>{ const box=$(`#${type}Box`); box.insertAdjacentHTML('beforeend', itemList([{name:'',point:0}],type)); };
window.closeModal=()=>$('#modal').className='modal'; window.recalcPreview=()=>{ const temp={scores:{},bonuses:[],penalties:[]}; $$('.scoreInput').forEach(i=>temp.scores[i.dataset.id]=Number(i.value||0)); $$('.bonusPoint').forEach((i,k)=>temp.bonuses.push({name:$$('.bonusName')[k]?.value||'',point:Number(i.value||0)})); $$('.penaltyPoint').forEach((i,k)=>temp.penalties.push({name:$$('.penaltyName')[k]?.value||'',point:Number(i.value||0)})); const c=calcEval(temp); $('#previewScore').textContent=c.total; const pr=$('#previewRank'); pr.textContent=c.rank.code; pr.className='tag '+c.rank.tag; };
window.saveEval=(id)=>{ const ev=id?state.evaluations.find(e=>e.id===id):{id:uid('ev'),year:state.selectedYear,period:state.selectedPeriod}; ev.employeeId=$('#evEmp').value; ev.status=$('#evStatus').value; ev.evidenceCount=Number($('#evEvidence').value||0); ev.note=$('#evNote').value; ev.scores={}; $$('.scoreInput').forEach(i=>ev.scores[i.dataset.id]=Number(i.value||0)); ev.bonuses=[]; $$('.bonusPoint').forEach((i,k)=>ev.bonuses.push({name:$$('.bonusName')[k]?.value||'',point:Number(i.value||0)})); ev.penalties=[]; $$('.penaltyPoint').forEach((i,k)=>ev.penalties.push({name:$$('.penaltyName')[k]?.value||'',point:Number(i.value||0)})); ev.workflow=ev.status==='draft'?'Giáo viên':'Tổ trưởng'; const errs=validateEval(ev).filter(x=>!x.includes('Kỳ đánh giá')||id); if(errs.length && ev.status!=='draft'){ $('#errBox').innerHTML=errs.map(e=>`<div class="alert">${e}</div>`).join(''); return; } if(!id) state.evaluations.push(ev); save(id?'Cập nhật phiếu đánh giá':'Tạo phiếu đánh giá'); toast('Đã lưu phiếu'); window.closeModal(); render(); };
window.delEval=id=>{ if(confirm('Xóa phiếu này?')){state.evaluations=state.evaluations.filter(e=>e.id!==id); save('Xóa phiếu đánh giá'); render();} };
window.toggleLock=()=>{ if(isLocked()) state.lockedPeriods=state.lockedPeriods.filter(p=>p!==state.selectedPeriod); else state.lockedPeriods.push(state.selectedPeriod); save((isLocked()?'Khóa':'Mở khóa')+' kỳ đánh giá'); render(); };
function workflow(){ const steps=['Giáo viên','Tổ trưởng','Ban giám hiệu','Hội đồng liên tịch','Hiệu trưởng','Đã khóa']; layout('Quy trình duyệt','Theo dõi hồ sơ từ tự đánh giá đến Hiệu trưởng chốt và khóa dữ liệu',`<div class="grid cards">${steps.map(s=>`<div class="card"><span>${s}</span><b>${evalsFiltered().filter(e=>(e.workflow||'Giáo viên')===s).length}</b></div>`).join('')}</div><div class="card" style="margin-top:16px"><div class="table-wrap"><table><thead><tr><th>CBGVNV</th><th>Điểm</th><th>Hiện tại</th><th>Chuyển bước</th></tr></thead><tbody>${evalsFiltered().map(e=>{const emp=state.employees.find(x=>x.id===e.employeeId)||{}; const c=calcEval(e); return `<tr><td>${emp.name}</td><td>${c.total}</td><td><span class="tag">${e.workflow||'Giáo viên'}</span></td><td>${steps.map(s=>`<button onclick="window.moveFlow('${e.id}','${s}')">${s}</button>`).join(' ')}</td></tr>`}).join('')}</tbody></table></div></div>`); }
window.moveFlow=(id,s)=>{ const e=state.evaluations.find(x=>x.id===id); e.workflow=s; save(`Chuyển hồ sơ sang ${s}`); render(); };
function employees(){ layout('CBGVNV','Quản lý cán bộ, giáo viên, nhân viên, tổ chuyên môn và phân quyền',`<div class="toolbar"><button class="primary" onclick="window.openEmp()">+ Thêm nhân sự</button></div><div class="table-wrap"><table><thead><tr><th>Mã CB</th><th>Họ tên</th><th>Tổ</th><th>Chức vụ</th><th>Quyền</th><th>Email</th><th>Trạng thái</th><th></th></tr></thead><tbody>${employeesFiltered().map(e=>`<tr><td>${e.code}</td><td><b>${e.name}</b></td><td>${e.department}</td><td>${e.position}</td><td><span class="tag">${e.role}</span></td><td>${e.email||''}</td><td>${e.active?'Đang làm':'Nghỉ'}</td><td><button onclick="window.openEmp('${e.id}')">Sửa</button></td></tr>`).join('')}</tbody></table></div><div id="modal" class="modal"></div>`); }
window.openEmp=(id='')=>{ const e=id?deep(state.employees.find(x=>x.id===id)):{id:'',code:'',name:'',department:state.departments[0],position:state.positions[3],role:'GIAO_VIEN',email:'',active:true}; const m=$('#modal'); m.className='modal open'; m.innerHTML=`<div class="dialog"><div class="dialog-head"><h2>Nhân sự</h2><button onclick="window.closeModal()">Đóng</button></div><div class="form"><label>Mã CB<input id="empCode" value="${e.code}"></label><label class="span2">Họ tên<input id="empName" value="${e.name}"></label><label>Tổ<select id="empDept">${state.departments.map(d=>`<option ${d===e.department?'selected':''}>${d}</option>`)}</select></label><label>Chức vụ<select id="empPos">${state.positions.map(d=>`<option ${d===e.position?'selected':''}>${d}</option>`)}</select></label><label>Quyền<select id="empRole">${state.roles.map(d=>`<option ${d===e.role?'selected':''}>${d}</option>`)}</select></label><label class="span2">Email<input id="empEmail" value="${e.email||''}"></label></div><div class="toolbar"><button class="primary" onclick="window.saveEmp('${id}')">Lưu</button>${id?`<button class="danger" onclick="window.delEmp('${id}')">Xóa</button>`:''}</div></div>`; };
window.saveEmp=(id)=>{ const e=id?state.employees.find(x=>x.id===id):{id:uid('emp'),active:true}; e.code=$('#empCode').value.trim(); e.name=$('#empName').value.trim(); e.department=$('#empDept').value; e.position=$('#empPos').value; e.role=$('#empRole').value; e.email=$('#empEmail').value.trim(); if(!e.code||!e.name) return toast('Thiếu mã hoặc họ tên'); if(!id) state.employees.push(e); save(id?'Cập nhật nhân sự':'Thêm nhân sự'); window.closeModal(); render(); };
window.delEmp=id=>{if(confirm('Xóa nhân sự?')){state.employees=state.employees.filter(e=>e.id!==id); save('Xóa nhân sự'); window.closeModal(); render();}};
function criteria(){ layout('Tiêu chí & thang điểm','Không hardcode: admin có thể sửa tiêu chí theo quy chế từng năm',`<div class="card"><div class="table-wrap"><table><thead><tr><th>Nhóm</th><th>Tiêu chí</th><th>Điểm tối đa</th><th>Bắt buộc</th><th></th></tr></thead><tbody>${state.criteria.map(c=>`<tr><td>${c.group}</td><td>${c.name}</td><td><input type="number" value="${c.max}" onchange="window.updCrit('${c.id}','max',this.value)"></td><td><input type="checkbox" ${c.required?'checked':''} onchange="window.updCrit('${c.id}','required',this.checked)"></td><td><button class="danger" onclick="window.delCrit('${c.id}')">Xóa</button></td></tr>`).join('')}</tbody></table></div><div class="footer-note">Tổng điểm tiêu chí hiện tại: ${state.criteria.reduce((a,c)=>a+Number(c.max),0)} / 100. Cần giữ đúng thang 30 điểm chung + 70 điểm kết quả nhiệm vụ.</div></div><div class="card" style="margin-top:16px"><h3>Thêm tiêu chí</h3><div class="form"><input id="cg" placeholder="Nhóm"><input id="cn" placeholder="Tên tiêu chí"><input id="cm" type="number" placeholder="Điểm tối đa"><button onclick="window.addCrit()" class="primary">Thêm</button></div></div>`); }
window.updCrit=(id,k,v)=>{ const c=state.criteria.find(x=>x.id===id); c[k]=k==='max'?Number(v):v; save('Cập nhật tiêu chí'); render(); }; window.delCrit=id=>{state.criteria=state.criteria.filter(c=>c.id!==id); save('Xóa tiêu chí'); render();}; window.addCrit=()=>{state.criteria.push({id:uid('c'),group:$('#cg').value,name:$('#cn').value,max:Number($('#cm').value||0),required:true}); save('Thêm tiêu chí'); render();};
function bonusPenalty(){ layout('Điểm cộng / trừ','Quản lý danh mục thành tích, sai phạm và mức điểm tự động',`<div class="grid two"><div class="card"><h3>Danh mục điểm cộng</h3>${bpTable('bonusTypes')}</div><div class="card"><h3>Danh mục điểm trừ</h3>${bpTable('penaltyTypes')}</div></div>`); }
function bpTable(key){ return `<div class="table-wrap"><table><thead><tr><th>Tên</th><th>Điểm</th><th></th></tr></thead><tbody>${state[key].map(x=>`<tr><td><input value="${x.name}" onchange="window.updBP('${key}','${x.id}','name',this.value)"></td><td><input type="number" value="${x.point}" onchange="window.updBP('${key}','${x.id}','point',this.value)"></td><td><button class="danger" onclick="window.delBP('${key}','${x.id}')">Xóa</button></td></tr>`).join('')}</tbody></table></div><button onclick="window.addBP('${key}')">+ Thêm</button>`; }
window.updBP=(key,id,k,v)=>{const x=state[key].find(i=>i.id===id); x[k]=k==='point'?Number(v):v; save('Cập nhật điểm cộng/trừ')}; window.delBP=(key,id)=>{state[key]=state[key].filter(i=>i.id!==id); save('Xóa danh mục điểm') ;render()}; window.addBP=key=>{state[key].push({id:uid(key),name:'Mục mới',point:1}); save('Thêm danh mục điểm'); render();};
function categories(){ const cats=['years','periods','departments','positions','roles']; layout('Danh mục hệ thống','Quản lý năm học, tháng đánh giá, tổ chuyên môn, chức vụ, phân quyền',`<div class="grid two">${cats.map(k=>`<div class="card"><h3>${k}</h3>${state[k].map((x,i)=>`<div class="form" style="grid-template-columns:1fr 70px;margin-bottom:8px"><input value="${x}" onchange="window.updCat('${k}',${i},this.value)"><button class="danger" onclick="window.delCat('${k}',${i})">Xóa</button></div>`).join('')}<button onclick="window.addCat('${k}')">+ Thêm</button></div>`).join('')}</div>`); }
window.updCat=(k,i,v)=>{state[k][i]=v; save('Cập nhật danh mục')}; window.delCat=(k,i)=>{state[k].splice(i,1); save('Xóa danh mục'); render()}; window.addCat=k=>{state[k].push('Mục mới'); save('Thêm danh mục'); render()};
function reports(){ const evs=evalsFiltered(); const rows=evs.map(e=>{const emp=state.employees.find(x=>x.id===e.employeeId)||{}; const c=calcEval(e); return {emp,c,e};}); layout('Báo cáo','Xuất Excel/CSV, báo cáo thu nhập tăng thêm, top điểm, cảnh báo quá hạn',`<div class="toolbar"><button class="primary" onclick="window.exportCSV()">Xuất CSV</button><button onclick="window.print()">In/PDF</button></div><div class="card print-area"><h2>Báo cáo đánh giá ${periodName(state.selectedPeriod)} - ${state.selectedYear}</h2><div class="table-wrap"><table><thead><tr><th>Mã</th><th>Họ tên</th><th>Tổ</th><th>Điểm</th><th>Xếp loại</th><th>Hệ số</th><th>Dự kiến chi</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.emp.code}</td><td>${r.emp.name}</td><td>${r.emp.department}</td><td>${r.c.total}</td><td>${r.c.rank.name}</td><td>${r.c.rank.coef}</td><td>${money(Math.max(r.c.rank.code==='HTNV'?500000:0, r.c.rank.code==='KHTNV'?0:state.settings.baseSalary*r.c.rank.coef))}</td></tr>`).join('')}</tbody></table></div></div>`); }
window.exportCSV=()=>{ const rows=[['Ma CB','Ho ten','To','Diem','Xep loai','He so']]; evalsFiltered().forEach(e=>{const emp=state.employees.find(x=>x.id===e.employeeId)||{};const c=calcEval(e);rows.push([emp.code,emp.name,emp.department,c.total,c.rank.code,c.rank.coef])}); const blob=new Blob(['\ufeff'+rows.map(r=>r.join(',')).join('\n')],{type:'text/csv;charset=utf-8'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='bao-cao-danh-gia.csv'; a.click(); };
function audit(){ layout('Nhật ký thay đổi','Truy vết chỉnh sửa điểm, khóa dữ liệu, duyệt hồ sơ',`<div class="card"><div class="table-wrap"><table><thead><tr><th>Thời gian</th><th>Người dùng</th><th>Hành động</th></tr></thead><tbody>${(state.audit||[]).map(l=>`<tr><td>${l.time}</td><td>${l.user}</td><td>${l.action}</td></tr>`).join('')}</tbody></table></div></div>`); }
function settings(){ layout('Cấu hình Firebase','Dán firebase-config.js, upload GitHub Pages, publish rules bảo mật',`<div class="grid two"><div class="card"><h3>Cấu hình nghiệp vụ</h3><div class="form"><label>Quota tổ<input type="number" step=".01" value="${state.settings.quotaTeam}" onchange="state.settings.quotaTeam=Number(this.value);save('Cập nhật quota tổ')"></label><label>Quota hội đồng<input type="number" step=".01" value="${state.settings.quotaCouncil}" onchange="state.settings.quotaCouncil=Number(this.value);save('Cập nhật quota hội đồng')"></label><label>Lương cơ bản<input type="number" value="${state.settings.baseSalary}" onchange="state.settings.baseSalary=Number(this.value);save('Cập nhật lương cơ bản')"></label><label>Trần điểm cộng<input type="number" value="${state.settings.bonusCap}" onchange="state.settings.bonusCap=Number(this.value);save('Cập nhật trần điểm cộng')"></label></div></div><div class="card"><h3>Kiểm tra trước bàn giao</h3><div class="alert">Đã tách danh mục, tiêu chí, nhân sự, đánh giá, báo cáo, audit log.</div><div class="alert">Firebase mặc định local nếu chưa cấu hình để tránh lỗi khi chạy GitHub.</div><div class="alert">Cần publish firestore.rules trong file bàn giao trước khi chạy thật.</div></div></div>`); }
async function tryFirebase(){ if(!firebaseConfig.apiKey){$('#syncStatus').textContent='Local mode - chưa cấu hình Firebase';return;} $('#syncStatus').textContent='Firebase config detected'; }
async function syncFirebase(){ save('Đồng bộ thủ công'); toast(firebaseConfig.apiKey?'Đã chuẩn bị đồng bộ Firebase (cần bật SDK trong môi trường online)':'Đang chạy Local. Hãy dán firebase-config.js trước.'); }
window.state=state; window.save=save;
init();
